#!/bin/bash

mkdir -p /etc/supervisor
mkdir -p /var/log/supervisor

cat << EOF > /etc/supervisor/supervisord.conf
[supervisord]
nodaemon=true
user=root
logfile = /var/log/supervisor/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=10
loglevel = info

[eventlistener:stdout] 
command = supervisor_stdout 
buffer_size = 100 
events = PROCESS_LOG 
result_handler = supervisor_stdout:event_handler
EOF

for file in $(ls /launch.d); do
cat << EOF >> /etc/supervisor/supervisord.conf
[program:$file]
command=$(cat /launch.d/$file)
stdout_events_enabled=true
stderr_events_enabled=true
EOF
done

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
tail -f /var/log/supervisor/*
